FROM arm32v7/nginx

# Copy settings and dependencies
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/errors.conf /etc/nginx/conf.d/errors.conf
COPY static /app
COPY ./entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
